// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzh_210eW7T-3nDq0N0z4aH-_DOI6ZpOM',
    appId: '1:772908651524:web:688a5354efd418412a1151',
    messagingSenderId: '772908651524',
    projectId: 'chat-app-9ea13',
    authDomain: 'chat-app-9ea13.firebaseapp.com',
    storageBucket: 'chat-app-9ea13.appspot.com',
    measurementId: 'G-913E47BZXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtOGpQ0rZRlI7164IX3jCenUOyvWmMH0',
    appId: '1:772908651524:android:49c9a01aa6771ef22a1151',
    messagingSenderId: '772908651524',
    projectId: 'chat-app-9ea13',
    storageBucket: 'chat-app-9ea13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATgLy5rnN3c0IrqMMP083J3mxMrJJedAE',
    appId: '1:772908651524:ios:d16d53f19fb5d3be2a1151',
    messagingSenderId: '772908651524',
    projectId: 'chat-app-9ea13',
    storageBucket: 'chat-app-9ea13.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATgLy5rnN3c0IrqMMP083J3mxMrJJedAE',
    appId: '1:772908651524:ios:d16d53f19fb5d3be2a1151',
    messagingSenderId: '772908651524',
    projectId: 'chat-app-9ea13',
    storageBucket: 'chat-app-9ea13.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzh_210eW7T-3nDq0N0z4aH-_DOI6ZpOM',
    appId: '1:772908651524:web:eeb0ec9d71a70f2b2a1151',
    messagingSenderId: '772908651524',
    projectId: 'chat-app-9ea13',
    authDomain: 'chat-app-9ea13.firebaseapp.com',
    storageBucket: 'chat-app-9ea13.appspot.com',
    measurementId: 'G-26RQVR8GCG',
  );
}
